// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgkqhmbhbxtpzwsvrted.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpna3FobWJoYnh0cHp3c3ZydGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTQwMTEsImV4cCI6MjA3MzMzMDAxMX0._eqj_FqlH_-yl3JWWlnaMJzEzkOTVghHAhXFNchlHso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});